### ISSUE TITLE
 No module named 'cyfusion'

### ISSUE THREAD

**Issue by UestcJay** [yinyunie/depth_renderer#4]
`(renderer) root@VGG-V100-LZ-2:~/lkq/depth_renderer# python depth_fusion.py
Traceback (most recent call last):
  File "depth_fusion.py", line 9, in <module>
    from external import pyfusion

  File "/root/lkq/depth_renderer/external/pyfusion/__init__.py", line 8, in <module>
    from cyfusion import *
ModuleNotFoundError: No module named 'cyfusion'`
many thanks for your great work. I follow the install step, but can not run the code. can you give me some help?

**Comment by harshpaal** [comment]
@UestcJay did you figure out the solution?

**Comment by UestcJay** [comment]
Then I did not use this repo...

**Comment by yinyunie** [comment]
could you try 'pip install cython'?

**Comment by wen-yuan-zhang** [comment]
You can refer to this issue :)
https://github.com/griegler/pyfusion/issues/1

**Comment by YuQiao0303** [comment]
As mentioned by @zParquet , the solution in https://github.com/griegler/pyfusion/issues/1 actually works for me.

Though there's an error saying "No module named 'cyfusion', I actually have a 'cyfusion.cpython-36m-x86_64-linux-gnu.so' under ./external/pyfusion. The solution is to make sure your device can find it, by running the following command:

```
export LD_LIBRARY_PATH=your_path/depth_renderer/external/pyfusion/build:$LD_LIBRARY_PATH
export PYTHONPATH=your_path/depth_renderer/external/pyfusion:$PYTHONPATH
```
